### ISSUE TITLE
Ngify:  A Browserify Transform for Angular - Michael A. Jackson

### ISSUE THREAD

**Issue by majgis** [AngularJSUtah/meetups#10]
Hello, I'm the creator of ngify, a browserify transform for angular:
https://www.npmjs.com/package/ngify

If you think it is of interest, I would be happy to present on a Tuesday.

**Comment by berwyn** [comment]
:+1:

**Comment by ghost** [comment]
I am now available to present on Thursday as well as Tuesday.

**Comment by rbdone** [comment]
Hey @majgis, I apologize for the delay, I've been meaning to reach out for a while. Are you still up  for presenting on this? You can have your choice on November 10th or December 8th :)

**Comment by ghost** [comment]
No problem.  This is an obscure topic and library and I'm doubting that the
majority will find it of interest.  I responded on the list because I
thought maybe something was better than nothing.  I'd say just use this
topic as a filler if you are unable to schedule something else.

**Comment by rbdone** [comment]
That sounds like a great plan, thanks for the suggestion! We'll plan on doing that then.

—

**Comment by ghost** [comment]
insufficient interest
