### ISSUE TITLE
An introduction to CSS next - Bret Little

### ISSUE THREAD

**Issue by blittle** [AngularJSUtah/meetups#11]
An introduction to what is new and coming in CSS and how you can use it now!

**Comment by mwinche** [comment]
+1

**Comment by berwyn** [comment]
:+1:

**Comment by jasonwaters** [comment]
:+1:

**Comment by jasonwaters** [comment]
Hey @blittle, any way we can persuade you to present about this on February 9th?

**Comment by rbdone** [comment]
:+1: Looking forward to it!

**Comment by jasonwaters** [comment]
Just circling back on this one, @blittle, do you still have interest in presenting on this topic (again)?

**Comment by blittle** [comment]
Not really. I'll submit another topic instead :)

**Comment by jasonwaters** [comment]
@blittle I figured as much.  Let me know what topic you'd like to present on, we'd love to have you speak soon!
