### ISSUE TITLE
Looking into ES7 Decorators - @berwyn

### ISSUE THREAD

**Issue by Xesued** [AngularJSUtah/meetups#12]
Typescript 1.5 and ES7 decorators are already starting to see great support.  Angular 2 comes with them as the preferred method of development.  This talk will give us a head start on decorators by learning what they are, how they work, and writing one ourselves that we can use today.

This talk will use Typescript 1.5.

**Comment by rbdone** [comment]
:+1: That sounds great! I would love to understand decorators better.

**Comment by mwinche** [comment]
:+1:

**Comment by berwyn** [comment]
:+1: Definitely would be great to see this

**Comment by blittle** [comment]
:+1:

**Comment by rbdone** [comment]
Hey @Xesued, I apologize for the delay, are you still up for presenting on this? We'd love to have you present!

If so, would one of our two upcoming meetups work for you? (November 10th or December 8th)

**Comment by Xesued** [comment]
I moved to Minnesota :disappointed: I'll take my name off if someone else wants to do this.  Thanks.

**Comment by rbdone** [comment]
Oh, that's right, I forgot you told me already. I didn't mentally match your username to our email discussion. Thanks again!

**Comment by berwyn** [comment]
I'd be willing to give this talk in @Xesued's place, it's a topic I've been diving into lately.

If you have any notes, Nathan, I'd love to steal them and compare to what I have!

**Comment by rbdone** [comment]
That would be awesome Jamison! We'd love to take you up on that!

Do you have a preference of one of those meetup dates?

—

**Comment by berwyn** [comment]
November 10th works for me

**Comment by rbdone** [comment]
Awesome, let's do it! Thanks Jamison!

I'll send you details about presenting in the next week or so.
