### ISSUE TITLE
Taking the C out of CSS: Better Angular applications with BEM -- Joel Denning

### ISSUE THREAD

**Issue by internettrans** [AngularJSUtah/meetups#14]
-A brief overview of why our CSS gets so messy
-BEM methodology's solution
-Why Angular and BEM are meant for each other
-Specifics (with examples) of best BEM practices for Angular code.

**Comment by rbdone** [comment]
:+1:

**Comment by rbdone** [comment]
Thanks again for presenting Joel! It was great!

-Ryan
