### ISSUE TITLE
Angular 2 Basics

### ISSUE THREAD

**Issue by rbdone** [AngularJSUtah/meetups#15]
Maybe you're an AngularJS 1.x ninja but haven't had the time to look at Angular 2.  Or maybe you're just getting started in this crazy awesome framework and need guidance of which version of Angular to start your next project with.  In both cases, you want to understand Angular 2 better.

This is a beginner's introduction to Angular 2. We'll build a simple app using some of the cool new features of Angular 2, and we'll talk about some of the differences between 1.x and 2.0.

**Comment by mwinche** [comment]
:+1:

**Comment by berwyn** [comment]
:+1:

**Comment by berwyn** [comment]
Do we have anyone to do this talk yet? Because if not, I've been doing a lot of work in Angular 2 lately and would be more than willing to take it!

**Comment by rbdone** [comment]
Dude, that would be awesome @berwyn. We had a short intro talk this month, but we definitely need more Angular 2 talks (at least one each month for a bit), so that would be great!

When would you like to do it? Would February 9th work for you?

**Comment by berwyn** [comment]
That works for me!

**Comment by rbdone** [comment]
Fantastic, thanks Jamison! We'll plan on it.

When you get it, send me a title and description of what you want to talk about and I'll add it to the meetup site.

**Comment by jasonwaters** [comment]
ok @berwyn , it's on like donkey kong – feb 9th.  Can't wait!

**Comment by jasonwaters** [comment]
Thanks @berwyn, you did great!  I loved the live coding.

**Comment by jasonwaters** [comment]
Can you add a link to your slides here for me?
