### ISSUE TITLE
Real-time web apps with Angular, Deepstream, and RethinkDB, aka "Build your own Firebase in 30 minutes" - Ryan Done

### ISSUE THREAD

**Issue by rbdone** [AngularJSUtah/meetups#16]
Real-time web apps are hard. Typical web apps have a stateful database, a stateful DOM, and kites of code in-between to try to keep the two in sync, but there's a better way. We can remove a lot of the boileri-mate code and moving pieces by switching to technologies that are better built to support your features. Enter RethinkDB and Deepstream.io.

I will show how you can easily use these two technologies to build your own open-source-based, real-time Firebase, and we'll throw a small angular app in for good measure.

**Comment by mwinche** [comment]
:+1:

**Comment by filoxo** [comment]
+1

**Comment by jasonwaters** [comment]
:+1:

**Comment by jasonwaters** [comment]
@rbdone did you already present on this topic?

**Comment by rbdone** [comment]
I don’t think I ever did… This topic is of less interest now because RethinkDB has come out with Horizon which is roughly equivalent to using Deepstream + Rethink.

On Thu, Aug 11, 2016 at 9:49 AM Jason Waters

<
mailto:Jason Waters notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/rbdone
did you already present on this topic?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/AngularJSUtah/meetups/issues/16#issuecomment-239203150
, or

**Comment by jasonwaters** [comment]
Ok, so close this issue then?

**Comment by rbdone** [comment]
Yep, sounds good. Unless a lot of folks are interested in it still.
