### ISSUE TITLE
AngularJS 1.X In ES6 - Angular With Classes - AJ Larson

### ISSUE THREAD

**Issue by twomoonsfactory** [AngularJSUtah/meetups#17]
Something I've enjoyed working with recently is working with ES6 syntax in the Angular environment.  It can be challenging to figure out using classes within the AngularJS framework however.  It would have helped my understanding immensely if I had heard a talk like this rather than piecing it together myself.

**Comment by rbdone** [comment]
This sounds like a great talk!  Would you be up for giving it in February?

**Comment by twomoonsfactory** [comment]
Absolutely!

**Comment by rbdone** [comment]
Awesome, we'll plan on it!  :+1:  If you want to adjust the title or description at all, let me know and I'll update/add it to Meetup.com

**Comment by twomoonsfactory** [comment]
I'll be able to take a look at it tonight, and will let you know! I have a
PC, any particular software I'll need for the presentation?

**Comment by rbdone** [comment]
Sounds great!

I believe they have a display port adapter, 15-pin VGA, and DVI adapters. If you don't have one of these, let us know and we'll round up and adapter.

As for software, they will have you download a flash plugin so we can record the presentation. Are you running Windows or Linux?

**Comment by mwinche** [comment]
:+1: super excited for this one @twomoonsfactory!

**Comment by twomoonsfactory** [comment]
Running Windows -- with a 15-pin VGA and an HDMI, so I should be fine.  I just noticed the propensity of Macs.  =]  And the title and all look fine to me.

Sounds like fun!

**Comment by jasonwaters** [comment]
Just wanted to follow up and confirm that you are good to go for this presentation on Feb 9th?
@twomoonsfactory

**Comment by twomoonsfactory** [comment]
Yes, I'm still planning on it!

**Comment by jasonwaters** [comment]
Excellent, I've got you scheduled.  Thanks!

**Comment by jasonwaters** [comment]
Hey AJ, thanks again for speaking.  You did great!  Good luck on your job hunt, I'm sure you'll get something quick.

The video recording on your cut off half of the slides.  I blame Adobe and their crappy recording software.

At any rate, would you mind sharing a url to your slides so people can view them?

**Comment by twomoonsfactory** [comment]
I thought this had sent, just saw the draft in my inbox, sorry!
https://slides.com/aj-larson/es-6-and-angular-1-x
I posted this in the Meetup comments too, let me know if there is anything
else I could do.

Thanks!
AJ
