### ISSUE TITLE
Reactive Programming - What is RxJS? - Jeremy Lund

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#19]

**Comment by mwinche** [comment]
:+1:

**Comment by lund0n** [comment]
@jasonwaters I would love to speak on this. The earliest I would be able to prepare this would be April.

**Comment by mwinche** [comment]
Okay then now I'm like:

> :+1: :+1: :+1: :+1: :clap:

**Comment by jasonwaters** [comment]
Excellent, I was hoping you'd volunteer for something.  I love hearing you present.

I'll put you down for April 12th!

**Comment by lund0n** [comment]
Thanks!

**Comment by rbdone** [comment]
Oh man, April is going to be awesome! I'm looking forward to hearing you present @lund0n!

**Comment by rbdone** [comment]
Jeremy, thank you again for presenting. It was very informative and it sounds like a lot of people enjoyed it!

**Comment by lund0n** [comment]
@rbdone Thanks for having me!
