### ISSUE TITLE
"Using Flux with Angular 1.x" - Derek Stobbe

### ISSUE THREAD

**Issue by rbdone** [AngularJSUtah/meetups#2]
Even without React, the principles of Flux architecture can give you big wins in Angular development. Let's talk about how.

**Comment by majgis** [comment]
+1  I am trying to implement a flux-like data flow.  This talk would provide me with immediate benefit.

**Comment by berwyn** [comment]
:+1:

**Comment by jasonwaters** [comment]
:+1:

**Comment by rbdone** [comment]
:+1:

**Comment by blittle** [comment]
Been messing around with flux concepts in angular 1.x, specifically with Immutable.js. I'm very interested to see what Derek has put together.
