### ISSUE TITLE
Immutable Data Structures and Why – Julia Gao

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#21]

**Comment by jasonwaters** [comment]
@ryoia looking forward to this!

**Comment by ryoia** [comment]
@jasonwaters me too! see you soon!

**Comment by mwinche** [comment]
:+1: Excited for this!

**Comment by rbdone** [comment]
:+1: I'm very interested in this topic! Thanks for volunteering @ryoia!

**Comment by rbdone** [comment]
Thank you again for presenting tonight Julia!! Well done, and it seemed to be well received as well
