### ISSUE TITLE
Large web apps using a plethora of libraries and frameworks - Joel Denning

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#23]
Does your organization use a vast array of javascript libraries and frameworks in the same app?  How do you make it work?

**Comment by blittle** [comment]
@joeldenning do you want to talk single-spa with this?

**Comment by internettrans** [comment]
Oh yes, this seems like single-spa would be an awesome talk for this. @jasonwaters I'd be happy to talk about this, at Canopy we're using an open source project that I created called [single-spa](https://github.com/CanopyTax/single-spa) which allows us to combine ng1, ng2, react, etc all in one app.

**Comment by jasonwaters** [comment]
@joeldenning I haven't heard of single-spa, but it sounds like the perfect solution and we'd love to have you present on it!  Can you do September 13th?

**Comment by internettrans** [comment]
Sure, September 13th works for me. Is that for the AngularJS Salt Lake (meets in South Jordan) or AngularJS Utah Valley (Adobe in Lehi)?

**Comment by jasonwaters** [comment]
@joeldenning Awesome!!  I've got you scheduled.  It's for the Utah Valley meetup at Adobe in Lehi

**Comment by jasonwaters** [comment]
Just wanted to give you two ( @jspenc72 and @joeldenning ) a heads up that I've got you both speaking on similar topics in September:

https://github.com/AngularJSUtah/meetups/issues/43
https://github.com/AngularJSUtah/meetups/issues/23

I think there is probably more than enough to cover on the subject, but want to make sure you each feel like there's not too much redundancy here.

**Comment by jspenc72** [comment]
I think there may be some overlap but I was planning on gearing my talk to those who are currently using ng1  and are looking for a path to upgrade their apps to ng 2 through a side by side approach...

**Comment by jspenc72** [comment]
I would talk about the side by side upgrade path in the official ng2 docs. Talk about challenges I've faced in doing this and if there is time, Demonstrate the process by showing a typical ng1 spa, setup ng2 and convert an ng1 directive to an ng2 component.

**Comment by blittle** [comment]
I think that @joeldenning's talk is more framework agnostic in the sense of how you can build an app with a variety of frameworks in harmony.

**Comment by jspenc72** [comment]
Agreed, with that being said i done think there is a problem with too much overlap.

**Comment by jasonwaters** [comment]
Ok, great.  Sounds like we'll have a great meetup in September then.  Thanks for volunteering fellas!

**Comment by jasonwaters** [comment]
Hey @joeldenning , We're looking forward to having you present on Tuesday!  The meetup starts at 6pm at the Adobe building.  If you can arrive a 10 mins early that would be great.  That way we can get you set up with wifi and mic'd ahead of time.

I've got you scheduled for 30 minutes.

**Comment by internettrans** [comment]
Great I'll be there!

Joel

**Comment by jasonwaters** [comment]
Thanks again for presenting @joeldenning !!
