### ISSUE TITLE
All about flexbox — Trudy Firestone

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#25]

**Comment by TruFire** [comment]
I'd be happy to speak on that at an upcoming meetup. I use flexbox at my job, and it's a lot of fun to work with. It makes layout in css a lot more like layout should be. There are cool websites where you can learn about it and play with flexbox, and I'd love to share them as well as my personal experience with it.

**Comment by filoxo** [comment]
It'd be great to also roll [CSS `grid`](https://css-tricks.com/snippets/css/complete-guide-grid/) into this talk.

**Comment by TruFire** [comment]
I'd be happy to research it and talk about that as well, but I haven't worked with it before.

**Comment by jasonwaters** [comment]
Hey @TrudyFirestone, we'd love to have you speak about flexbox! Any chance you could be ready to present for our upcoming Meetup on Oct 11th?

**Comment by TruFire** [comment]
I'd be happy to @jasonwaters, assuming you're still looking for someone? How long should the presentation be?

**Comment by jasonwaters** [comment]
@TrudyFirestone Presentations are typically 30 mins, with two presentations at each meeting. Our other speaker will be discussing a CSS related topic as well, so it would be a perfect combo!

What do you say, are you in?

**Comment by TruFire** [comment]
Sounds great. I'm in and looking forward to it @jasonwaters.

**Comment by jasonwaters** [comment]
Thanks @TrudyFirestone ! Looking forward to it!

If you can, please arrive at Adobe 10 mins before we begin so we can get you set up.

**Comment by TruFire** [comment]
That's 5:50, right? Will do @jasonwaters

**Comment by TruFire** [comment]
Presentation: https://trudyfirestone.github.io/AllAboutFlexboxPresentation/ 
Source: https://github.com/TrudyFirestone/AllAboutFlexboxPresentation
