### ISSUE TITLE
Array tips and tricks: forEach, map, filter, reduce – Jesse Bahr

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#26]

**Comment by jessebahr** [comment]
I can speak on this if you'd like.

What about other methods, too - I'm thinking of sort, find, join, and concat?

**Comment by jasonwaters** [comment]
Excellent!!  Yes any and all array tips you want to talk about would be awesome!  We are filling up fast, looks like I can schedule it for June 14.  Does that work for you?

**Comment by jessebahr** [comment]
Sure, June 14th works.

**Comment by rbdone** [comment]
:+1: Thanks for volunteering @jessebahr! I'm looking forward to it.

**Comment by mwinche** [comment]
@jessebahr Just wanted to confirm that you're still good for the 14th of June (this coming Tuesday).

**Comment by jessebahr** [comment]
I am! It's going to be awesome.

**Comment by mwinche** [comment]
Great! I look forward to it!
