### ISSUE TITLE
"HTML5: Intro to Canvas" - Jason Waters

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#3]
Curious about the HTML5 Canvas Element?  Should you use it instead of SVG?

This intro will get you started.

**Comment by rbdone** [comment]
:+1:

**Comment by blittle** [comment]
@jasonwaters will this have an angular twist? Or does that not really matter for AngularJS Utah?

**Comment by jasonwaters** [comment]
It will be geared more towards the canvas element and what it can do.  There will be a little angular, but just trivial stuff to showcase canvas.

I know the group is AngularJS focused, so this training may not be as interesting if folks are only coming to take their angular skills to the next level.

**Comment by blittle** [comment]
Sweet. I am all for improving JS knowledge over just Angular. More curious to know the goal of the group.

**Comment by rbdone** [comment]
I am all about supporting improving general JS knowledge!  I want to
support community growth as a whole, not just with Angular.

It just happens that Angular is currently a great catalyst for discussion :)

**Comment by rbdone** [comment]
Jason, is this a talk that you want to give?  Or should I add a label "Looking for speaker"

**Comment by jasonwaters** [comment]
@rbdone I'm planning to give this one.

**Comment by rbdone** [comment]
Awesome, I've added you to it the same way I've done the others.

**Comment by mwinche** [comment]
:+1: I want to see @jasonwaters speak!
