### ISSUE TITLE
Google Analytics + AngularJS == Awesome – Danny Fenstermaker

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#30]

**Comment by jasonwaters** [comment]
@dfenstermaker looking forward to this!

**Comment by dfenstermaker** [comment]
Awesome cant wait!

**Comment by mwinche** [comment]
@dfenstermaker Excited to have you speaking again!

**Comment by rbdone** [comment]
Well done the other night Danny! I heard many comments afterward in appreciation of your talk!

Thank you again for speaking!
