### ISSUE TITLE
Angular 2 Style Guide

### ISSUE THREAD

**Issue by jasonwaters** [AngularJSUtah/meetups#31]
https://github.com/johnpapa/angular-styleguide/blob/master/a2/README.md

**Comment by ryandivis** [comment]
Now we have the official style guide https://angular.io/styleguide. Codelyzer (https://github.com/mgechev/codelyzer) has been introduced to help with static code style checking.

**Comment by jasonwaters** [comment]
Thanks for the info @ryandivis!  Do you have any interest in presenting on the official style guide or Codelyzer?

**Comment by ryandivis** [comment]
sure, I'd be willing to present on the style guide and codelyzer

**Comment by jasonwaters** [comment]
@ryandivis very cool, thanks for volunteering!  Does July 12th work for you? (We are full for June)

**Comment by ryandivis** [comment]
@jasonwaters July 12th works for me

**Comment by jasonwaters** [comment]
Great, thanks.  I've got you scheduled.  Looking forward to it!

**Comment by mwinche** [comment]
Just following up, @ryandivis does July 12th still work for you?

**Comment by ryandivis** [comment]
Still works for me. I should have my presentation done tomorrow or Thursday. 

```
On Tuesday, July 5, 2016 4:10 PM, Matt Winchester <notifications@github.com> wrote:
```

 Just following up, @ryandivis does July 12th still work for you?—

**Comment by mwinche** [comment]
Sweet, thanks @ryandivis!

**Comment by mwinche** [comment]
If you can please plan on showing up 10-15 minutes early. We're going to need to get you hooked up to the Adobe Connect session before we start.

See you then!
