### ISSUE TITLE
Google Material Design - Tyler Wall 

### ISSUE THREAD

**Issue by wallter** [AngularJSUtah/meetups#39]
I'm _tentatively_ volunteering to present on something between: UX, usability, conversion optimization, and Google Material Design. 

I am by no means an expert in any of the topics, but I do know—and have—a good amount of knowledge+time surrounding the topic(s).

I wouldn't know where to start or what aspects of...`/(ux|usability|conversion\s?optimization|(?:go*gle)\s?material design)/`  ... to go over. 

**Requests / Ideas?**

**Comment by mwinche** [comment]
Thanks for submitting this Tyler! I don't think this is a topic we have heard enough about and I was literally just thinking about how I'd like to learn more about usability in general.

I'd give the topic a 👍

**Comment by wallter** [comment]
What areas would you be most interested in learning more about?

**Comment by mwinche** [comment]
Well I'd say its pretty broad and there is probably an element of "I don't know what I don't know" but in general I'd just want to learn about what makes an application usable.

**Comment by MrGrigri** [comment]
I believe it would be useful from my perspective to see how to create an Angular Directive that handles a particular Material Design component like a FAB. Kind of line [Angular Material](https://material.angularjs.org/latest/) for example, but more personalized.

**Comment by jasonwaters** [comment]
Hey @wallter, We'd love to hear from you on this topic!  When would you like to present? We've got availability on these upcoming dates:
- Sept 13th
- Oct 11
- Nov 8
- Dec  13
