### ISSUE TITLE
"Reflection: Angular templates with lodash" - Bret Little

### ISSUE THREAD

**Issue by blittle** [AngularJSUtah/meetups#4]
Lets talk about lodash and how it can easily be married to Angular. Using a six line filter, I will expose the power of lodash directly within angular templates. This will be an introduction to lodash, angular templates, and we'll talk about scope and reflection within JavaScript.

Spoiler:
```javascript
angular.module('app')
	.filter('lodash', function() {
		return function(input, method) {
			var args = [input].concat(Array.prototype.slice.call(arguments, 2));
			return _[method].apply(_, args);
		}
	});
```

**Comment by rbdone** [comment]
This is cool.  Can you show an example of how you would use it?

**Comment by blittle** [comment]
More spoilers:
```html
<div>{{ data | lodash:"findWhere":{id: 9999} }}</div>
<div ng-repeat="i in 10 | lodash:'range'">{{ $index }}</div>
```

**Comment by blittle** [comment]
An important note about this stuff: the purpose of this presentation is also largely to explain some of the fun parts of JavaScript (dynamic function invocation with reflection, dynamic arguments, etc). I don't necessarily encourage putting complex logic throughout your templates with lodash, though there may be times it is appropriate. Just because you can, doesn't mean you should ;)

**Comment by rbdone** [comment]
Love it!  :+1:

**Comment by mwinche** [comment]
Sounds cool! :+1:

**Comment by rbdone** [comment]
Great preso Bret!  Thanks again!

-Ryan
