### ISSUE TITLE
A beginner's guide to ASTs

### ISSUE THREAD

**Issue by kentcdodds** [AngularJSUtah/meetups#41]
Hey all! I realize this isn't really Angular-specific at all, but I'm giving a talk at a conference this month and I'd love an opportunity to practice it at a meetup beforehand. Here's the abstract:

> The Abstract Syntax Tree. It sounds a lot worse than it is. It’s actually quite simple and enables some powerful tools. BabelJS uses it to transform your code from ES.Next to ES5. ESLint uses it to lint your code. And with a knowledge of how it works, you can extend these and other tools to do some mind bustingly powerful things. Prepare to be amazed by ASTs!

I think the crowd would be interested in this 👍

**Comment by mwinche** [comment]
:+1: 

Talks don't have to be about Angular, just relevant to Angular Devs. I know I've done some fun stuff with esprima in years past, curious to see what you have cooked up!

**Comment by kentcdodds** [comment]
Awesome! So do I take it that I've been accepted?

**Comment by mwinche** [comment]
We just need to schedule you now, June is already full up, we have an opening on July 12th, if you're available.

**Comment by kentcdodds** [comment]
Ah, yeah... I was really hoping to give this before my talk in Kansas City in two weeks so I could practice it. No worries. I knew it was a long shot to get a spot on such short notice. I'm not certain that I'll be able to make it on the 12th. Ping me if you're having trouble finding someone to speak and I'll probably be able to make it work.

**Comment by mwinche** [comment]
Okay how about this, if one of my speakers falls through, would you be available as a backup? (Meetup is in one week June 14).

**Comment by kentcdodds** [comment]
Sure! If you find out beforehand that one of the speakers can't make it, let me know and I'll fill in for you (just give me a day notice or so, so I can plan on it).

**Comment by mwinche** [comment]
Can do, I was going to confirm with them pretty soon.

**Comment by jasonwaters** [comment]
@mwinche Perhaps one of our speakers for this month would like to reschedule to the following month?

**Comment by kentcdodds** [comment]
No pressure. I realize that I was a bit late in the game. But if someone would rather have more time to prepare their talk or something that'd be a win-win :-)

**Comment by mwinche** [comment]
So Chad asked to postpone until next month, you still up for it @kentcdodds?

**Comment by kentcdodds** [comment]
Sure! Let's do it :D
