### ISSUE TITLE
Angular 1 and Angular 2 Side By Side - Jesse Spencer

### ISSUE THREAD

**Issue by jspenc72** [AngularJSUtah/meetups#43]
- I would like to hear or give a talk about running ng1 and ng2 side by side.

This will be very useful to those interested in migrating "legacy" apps.

Here are a few useful links on the topic:

https://angular.io/docs/ts/latest/guide/upgrade.html#!#bootstrapping-hybrid-angular-1-2-applications

https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-angular-1-component-directives-from-angular-2-code

**Comment by jasonwaters** [comment]
@jspenc72 Ok, i've got you down to present on this for the 13th.  The meetup is at the Adobe building in Alpha Bravo (the big room next to the cafeteria).  We start promptly at 6pm.

**Comment by jasonwaters** [comment]
Hey @jspenc72, We're looking forward to having you present on Tuesday!  The meetup starts at 6pm at the Adobe building.  If you can arrive a 10 mins early that would be great.  That way we can get you set up with wifi and mic'd ahead of time.

I've got you scheduled for 30 minutes.

**Comment by jspenc72** [comment]
Ok 30 min should be plenty.

**Comment by jasonwaters** [comment]
Thanks again for presenting @jspenc72 !

**Comment by zhenwenc** [comment]
Hi, any chance there is a video you could share the experience? Currently having trouble with the angular-route while running NG1 and NG2 side by side, where my new NG2 component doesn't render with its template. I would like to learn a bit more. Thanks!

**Comment by jasonwaters** [comment]
@zhenwenc unfortunately, this meetup was not recorded.  😢
