### ISSUE TITLE
"ES6, Webpack and Angular: Getting Started" - Danny Fenstermaker

### ISSUE THREAD

**Issue by rbdone** [AngularJSUtah/meetups#7]
From Danny:
"Let's get started with ES6, having made the switch to the latest version of javascript has been a great move for me. I would like to share the process of taking your current javascript apps, or starting new ones and bringing them into the now. I will be discussing setting up Webpack bundling, bootstrapping Angular, getting the Webpack bundle ready for production and getting a Webpack Dev Server up and running for super fast development. "

**Comment by rbdone** [comment]
I'm really excited to learn about Webpack and ES6, and from what I know of Danny, he's super sharp.  I haven't heard him present, but I'm excited to. :+1:

**Comment by berwyn** [comment]
:+1:
