### ISSUE TITLE
"Hands on: Get Started Writing and Testing Angular Directives" - Ben Loveridge (@bloveridge)

### ISSUE THREAD

**Issue by rbdone** [AngularJSUtah/meetups#8]
From @bloveridge:
"When considering AngularJS, you might find yourself overwhelmed with examples of data binding, controllers, form validation... it's a long list. But what should really get you excited about AngularJS are directives! Directives might not quite be the Answer to the Ultimate Question of Life, the Universe, and Everything, but in regards to AngularJS they come pretty close.

We'll show examples of each directive type and discuss the basic directive options. We'll also talk about when you should use directives and how you can use them to make your code simpler and more maintainable.

Have your favorite IDE ready if you want to follow along as we build a directive from scratch, complete with unit tests running automatically with karma."

**Comment by bloveridge-demos** [comment]
I've come to realize that the title and description feel a bit at odds. The description indicates this is a beginner lecture, while the title can lead people to believe it's more advanced.

Perhaps the title should be changed to "Hands on: Get Started Writing and Testing Angular Directives".

**Comment by rbdone** [comment]
Cool beans, I've updated it

**Comment by mwinche** [comment]
I know that directives are a common topic that people like to hear about. Do have much interest from our meetup folk for this?

**Comment by rbdone** [comment]
Hey @bloveridge, we had a lot of beginners at last night's meetup, and I think this topic would be _super_ valuable for them.  Are you up for presenting this at one of our upcoming meetups? (November 10th or December 8th)

**Comment by putermancer** [comment]
Yes. Either day should work for me, but I have a slight preference for November 10. Let me know what works out best.

**Comment by rbdone** [comment]
Awesome, let's plan on November 10th then. I'll send you more info via email. Thanks!
