### ISSUE TITLE
"Using Angular Material to create beautiful, accessible applications" - Maureen (@mkbotoman)

### ISSUE THREAD

**Issue by rbdone** [AngularJSUtah/meetups#9]
Angular Material's library of directives, css, layout, and promise-based services can be used to quickly put together an app that is beautiful and accessible.

I'd like to see a talk discussing:
* Quick basic layout and the layout attributes you can use to minimize the custom CSS you need.
* Promise-based services to create dialogs, bottom sheets, and toasts
* Any gotchas and rough edges that might exist (it's not at 1.0 yet after all)
* Custom theming using the theme provider
* Working with icons and the icon provider

**Comment by mkbotoman** [comment]
:+1: 

I am moving to SLC in a couple weeks, and couple potentially give this talk if its something people are interested in. I converted my current companies product to using a material front end about 7 months ago and have been iterating on it since.

**Comment by rbdone** [comment]
@mkbotoman that sounds fantastic, thanks for volunteering!

I'm certainly interested but I don't know about the rest of the community on this one. I'll add you to the talk title and let's gauge interest over the next few weeks.

**Comment by rbdone** [comment]
And welcome to SLC @mkbotoman!

**Comment by berwyn** [comment]
:+1:

**Comment by brettgpalmer** [comment]
I'm also interested in seeing a presentation on Angular Material.  The project looks very promising but its still very new.  I'm working on a new Angular project would like to use Material but wanted more information from the group.

**Comment by mwinche** [comment]
:+1:

**Comment by willaustin** [comment]
:+1:

**Comment by rbdone** [comment]
Hey @mkbotoman, lots of interest for your preso (both here and talking with folks at the meetups)!

Are you up for presenting at one of our upcoming meetups (Aug 11th or Sep 8th)?

**Comment by rbdone** [comment]
Hey @mkbotoman, lots of interest for your preso (both here and talking with folks at the meetups)!

Are you up for presenting at one of our upcoming meetups (Aug 11th or Sep 8th)?

**Comment by mkbotoman** [comment]
I have to put together a presentation so Aug 11th might be a little soon, but Sept 8 would work for me. How long are presentations normally?

**Comment by rbdone** [comment]
Awesome, that would be great!

We try to keep them to 30 minutes. Is that enough time for you?

Email me and I can give you more details: rbdone@gmail.com (<- this is me trusting google's spam filter :) )
